"""合规授权数据 Evidence Intake Gateway（GOLD-005）。

本包提供**独立于** Collector / Scheduler / Alpha 的证据接收与审计入口：

- :mod:`src.evidence.contracts`：版本化输入契约（``evidence-intake-v1``，Author / News）；
- :mod:`src.evidence.validation`：逐行机械校验（授权 / 来源身份 / 时间语义 / 内容完整性）；
- :mod:`src.evidence.intake`：validate-first / dry-run-first 的导入引擎
  （幂等、坏行隔离、append-only 落 ``raw_items`` + ``processed_items``）；
- :mod:`src.evidence.report`：Markdown 报告 + quarantine JSONL 载荷（全部脱敏）；
- :mod:`src.evidence.templates`：Author / News 的 operator-ready 输入模板（GOLD-006），
  模板行带显式 synthetic/example 标记，导入时判 ``SYNTHETIC_EVIDENCE`` 隔离、绝不计入；
- :mod:`src.evidence.ledger`：只读台账，供 GOLD-004 资格观测层统计
  "经证据入口认证且具备独立历史可用证据"的记录；
- :mod:`src.evidence.workflow`：operator 工作流的写入门禁与隔离摘要（GOLD-007），
  显式写入前二次验证；只允许 ``ACCEPTED`` 行 append-only 落库；
- :mod:`src.evidence.author_chain`：**gateway-only** 作者归属链（GOLD-007），
  只消费已通过证据入口的 Author 证据，普通 CSV / 历史样本无法绕过；
- :mod:`src.evidence.inbox`：**纯本地只读**的 Evidence Inbox 发现与预检（GOLD-011）：
  只扫描**显式** ``--inbox-dir``，候选包必须由 ``manifest.json`` 显式关联证据文件
  （含内容 SHA-256），复用 gateway 的契约 / 引用校验 / 逐行机械校验 / 原因码 / 脱敏，
  生成**脱敏**的 discovered / preflight_pass / quarantined / requires_human_action artifact，
  **绝不**移动或删除原始 evidence、绝不自动 intake、绝不解除 ``PHASE3_3_DATA``。

红线（与 `.clinerules` 一致）：

- 不联网、不抓取、不绕过 robots / 条款 / 证书；不把"公开可访问"当作采集或训练授权；
- 不伪造 ``published_at`` / ``collected_at`` / ``effective_at`` / 历史可用时间；
- 不覆盖历史事实（只 append-only；内容冲突判 ``IDENTITY_CONFLICT`` 并隔离）；
- 不因代码完成或 Mock 测试解除 ``PHASE3_3_DATA``。

入口：``scripts/intake_evidence.py``（单步 intake）与 ``scripts/evidence_operator.py``
（GOLD-007 单入口 operator workflow；两者均默认 dry-run、默认零写入、默认零网络）；
``scripts/evidence_inbox.py``（GOLD-011 只读发现 + 预检；唯一写入口是显式 ``--out``）。
"""

from __future__ import annotations

from src.evidence.author_chain import (
    AUTHOR_CHAIN_NOTE,
    AUTHOR_CHAIN_SCHEMA_VERSION,
    AuthorChainReport,
    GatewayAuthorEvidence,
    attribute_gateway_author_evidence,
    gateway_author_evidence,
    load_gateway_author_evidence,
)
from src.evidence.contracts import (
    ALLOWED_AUTHORIZATION_BASES,
    COMMON_REQUIRED_FIELDS,
    EVIDENCE_CONTRACT_VERSION,
    EVIDENCE_SCHEMA_VERSION,
    EXAMPLE_MARKER_FLAG_FIELDS,
    EXAMPLE_MARKER_KIND_FIELDS,
    EXAMPLE_MARKER_VALUES,
    QUARANTINE_REASON_CODES,
    AuthorizationDeclaration,
    EvidenceScope,
    ReasonCode,
    RowStatus,
    required_field_names,
    synthetic_marker_fields,
)
from src.evidence.handoff import (
    BLOCKED_STATUS,
    CHECK_CATEGORIES,
    HANDOFF_NOTE,
    HANDOFF_REPORT_NAME,
    HANDOFF_SCHEMA_VERSION,
    PENDING_HUMAN_REVIEW_STATUS,
    ChecklistItem,
    EvidenceHandoffReport,
    ExcludedEvidence,
    ScopeGap,
    build_evidence_checklist,
    build_excluded_evidence,
    build_handoff_report,
    render_handoff_markdown,
)
from src.evidence.inbox import (
    EXIT_NO_CANDIDATES,
    EXIT_UNUSABLE,
    FILE_ENTRY_REQUIRED_FIELDS,
    INBOX_NOTE,
    INBOX_REPORT_KIND,
    INBOX_REPORT_NAME,
    INBOX_SCHEMA_VERSION,
    MANIFEST_FILE_NAME,
    MANIFEST_REQUIRED_FIELDS,
    MAX_PATH_CHARS,
    PENDING_FILE_NAME,
    PENDING_KIND,
    PENDING_LOCK_SUFFIX,
    SUPPORTED_FILE_FORMATS,
    CandidatePackage,
    InboxArtifactWriteError,
    InboxDirError,
    InboxError,
    InboxPreflightReport,
    InboxReasonCode,
    InboxStatus,
    ManifestFileRef,
    PendingEntry,
    PendingRegister,
    PendingStateError,
    load_pending_register,
    render_inbox_summary,
    run_inbox_scan,
    scan_inbox,
    write_pending_register,
)
from src.evidence.inbox import exit_code_for as inbox_exit_code_for
from src.evidence.intake import (
    EvidenceIntakeReport,
    InputFile,
    InputRow,
    IntakeCounts,
    RowOutcome,
    intake_evidence,
    load_input_rows,
    read_input_file,
    resolve_format,
)
from src.evidence.ledger import (
    EvidenceLedger,
    ScopeLedger,
    ledger_from_raw_json,
    load_evidence_ledger,
)
from src.evidence.readiness_runner import (
    DEFAULT_JOURNAL_LIMIT,
    EVENTS_FILE_NAME,
    EXIT_BLOCKED,
    EXIT_CONFIG_ERROR,
    EXIT_LOCK_CONFLICT,
    EXIT_OK,
    EXIT_QUALIFICATION_FAILED,
    EXIT_STATE_INVALID,
    EXIT_WORKDIR_UNUSABLE,
    LOCK_FILE_NAME,
    LOCK_KIND,
    RUNNER_NOTE,
    RUNNER_REPORT_NAME,
    RUNNER_SCHEMA_VERSION,
    STATE_FILE_NAME,
    STATUS_FILE_NAME,
    STATUS_KIND,
    ArtifactWriteError,
    LockConflictError,
    LockInfo,
    LockUnavailableError,
    QualificationError,
    RunnerError,
    SingleInstanceLock,
    SnapshotBuilder,
    TickPaths,
    TickReport,
    TickStateError,
    WorkDirError,
    build_snapshot_from_session,
    exit_code_for,
    load_event_journal,
    render_tick_summary,
    run_tick,
    write_event_journal,
    write_status,
)
from src.evidence.readiness_watch import (
    SCOPE_STATE_FIELDS,
    SNAPSHOT_KIND,
    SNAPSHOT_SCHEMA_VERSION,
    WATCH_EVENT_KIND,
    WATCH_NOTE,
    WATCH_REPORT_NAME,
    WATCH_SCHEMA_VERSION,
    ReadinessSnapshot,
    ScopeChange,
    ScopeSnapshot,
    SnapshotStateError,
    WatchEvent,
    WatchEventType,
    atomic_write_text,
    build_snapshot,
    detect_changes,
    load_snapshot_state,
    render_watch_summary,
    write_events,
    write_snapshot_state,
)
from src.evidence.report import quarantine_payload, render_intake_report
from src.evidence.templates import (
    EXAMPLE_MARKER_COLUMNS,
    TEMPLATE_FORMATS,
    TEMPLATE_ROOT,
    TEMPLATE_SCHEMA_VERSION,
    example_rows,
    render_template,
    template_columns,
    template_output_name,
    write_template,
)
from src.evidence.validation import (
    EvidenceRecord,
    NormalizedRow,
    RowAssessment,
    assess_row,
    normalize_input_row,
)
from src.evidence.workflow import (
    OPERATOR_STEPS,
    OPERATOR_WORKFLOW_SCHEMA_VERSION,
    WRITE_GATE_NOTE,
    QuarantineEntry,
    QuarantineSummary,
    WriteGateDecision,
    build_quarantine_summary,
    evaluate_write_gate,
    render_quarantine_summary,
    render_write_gate,
)

__all__ = [
    "ALLOWED_AUTHORIZATION_BASES",
    "AUTHOR_CHAIN_NOTE",
    "AUTHOR_CHAIN_SCHEMA_VERSION",
    "BLOCKED_STATUS",
    "CHECK_CATEGORIES",
    "COMMON_REQUIRED_FIELDS",
    "DEFAULT_JOURNAL_LIMIT",
    "EVIDENCE_CONTRACT_VERSION",
    "EVIDENCE_SCHEMA_VERSION",
    "EXAMPLE_MARKER_COLUMNS",
    "EXAMPLE_MARKER_FLAG_FIELDS",
    "EXAMPLE_MARKER_KIND_FIELDS",
    "EXAMPLE_MARKER_VALUES",
    "EVENTS_FILE_NAME",
    "EXIT_BLOCKED",
    "EXIT_CONFIG_ERROR",
    "EXIT_LOCK_CONFLICT",
    "EXIT_NO_CANDIDATES",
    "EXIT_OK",
    "EXIT_QUALIFICATION_FAILED",
    "EXIT_STATE_INVALID",
    "EXIT_UNUSABLE",
    "EXIT_WORKDIR_UNUSABLE",
    "FILE_ENTRY_REQUIRED_FIELDS",
    "HANDOFF_NOTE",
    "HANDOFF_REPORT_NAME",
    "HANDOFF_SCHEMA_VERSION",
    "INBOX_NOTE",
    "INBOX_REPORT_KIND",
    "INBOX_REPORT_NAME",
    "INBOX_SCHEMA_VERSION",
    "LOCK_FILE_NAME",
    "LOCK_KIND",
    "MANIFEST_FILE_NAME",
    "MANIFEST_REQUIRED_FIELDS",
    "MAX_PATH_CHARS",
    "OPERATOR_STEPS",
    "OPERATOR_WORKFLOW_SCHEMA_VERSION",
    "PENDING_FILE_NAME",
    "PENDING_HUMAN_REVIEW_STATUS",
    "PENDING_KIND",
    "PENDING_LOCK_SUFFIX",
    "QUARANTINE_REASON_CODES",
    "RUNNER_NOTE",
    "RUNNER_REPORT_NAME",
    "RUNNER_SCHEMA_VERSION",
    "SCOPE_STATE_FIELDS",
    "SNAPSHOT_KIND",
    "SNAPSHOT_SCHEMA_VERSION",
    "STATE_FILE_NAME",
    "STATUS_FILE_NAME",
    "STATUS_KIND",
    "SUPPORTED_FILE_FORMATS",
    "TEMPLATE_FORMATS",
    "TEMPLATE_ROOT",
    "TEMPLATE_SCHEMA_VERSION",
    "WATCH_EVENT_KIND",
    "WATCH_NOTE",
    "WATCH_REPORT_NAME",
    "WATCH_SCHEMA_VERSION",
    "WRITE_GATE_NOTE",
    "ArtifactWriteError",
    "AuthorizationDeclaration",
    "AuthorChainReport",
    "CandidatePackage",
    "ChecklistItem",
    "EvidenceHandoffReport",
    "EvidenceIntakeReport",
    "EvidenceLedger",
    "EvidenceRecord",
    "EvidenceScope",
    "ExcludedEvidence",
    "GatewayAuthorEvidence",
    "InboxArtifactWriteError",
    "InboxDirError",
    "InboxError",
    "InboxPreflightReport",
    "InboxReasonCode",
    "InboxStatus",
    "InputFile",
    "InputRow",
    "IntakeCounts",
    "LockConflictError",
    "LockInfo",
    "LockUnavailableError",
    "ManifestFileRef",
    "NormalizedRow",
    "PendingEntry",
    "PendingRegister",
    "PendingStateError",
    "QualificationError",
    "QuarantineEntry",
    "QuarantineSummary",
    "ReadinessSnapshot",
    "ReasonCode",
    "RowAssessment",
    "RowOutcome",
    "RowStatus",
    "RunnerError",
    "ScopeChange",
    "ScopeGap",
    "ScopeLedger",
    "ScopeSnapshot",
    "SingleInstanceLock",
    "SnapshotBuilder",
    "SnapshotStateError",
    "TickPaths",
    "TickReport",
    "TickStateError",
    "WatchEvent",
    "WatchEventType",
    "WorkDirError",
    "WriteGateDecision",
    "assess_row",
    "atomic_write_text",
    "attribute_gateway_author_evidence",
    "build_evidence_checklist",
    "build_excluded_evidence",
    "build_handoff_report",
    "build_quarantine_summary",
    "build_snapshot",
    "build_snapshot_from_session",
    "detect_changes",
    "evaluate_write_gate",
    "example_rows",
    "exit_code_for",
    "gateway_author_evidence",
    "inbox_exit_code_for",
    "intake_evidence",
    "ledger_from_raw_json",
    "load_event_journal",
    "load_evidence_ledger",
    "load_gateway_author_evidence",
    "load_input_rows",
    "load_pending_register",
    "load_snapshot_state",
    "normalize_input_row",
    "quarantine_payload",
    "read_input_file",
    "render_handoff_markdown",
    "render_inbox_summary",
    "render_intake_report",
    "render_quarantine_summary",
    "render_template",
    "render_tick_summary",
    "render_watch_summary",
    "render_write_gate",
    "required_field_names",
    "resolve_format",
    "run_inbox_scan",
    "run_tick",
    "scan_inbox",
    "synthetic_marker_fields",
    "template_columns",
    "template_output_name",
    "write_event_journal",
    "write_events",
    "write_pending_register",
    "write_snapshot_state",
    "write_status",
    "write_template",
]
